import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import AMMDemonstration from "../components/AMMDemonstration";
import DMMDemonstration from "../components/DMMDemonstration";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amplification in Liquidity Pools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Amplification in an Automated Market Maker
        </h1>

        {/* <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}

        <div className={styles.grid}>
          <div className={styles.section}>
            <h2>Typical Liquidity Pool</h2>
            <p className={styles.code}> x * y = k</p>
            <p className={styles.description}>
              {`In constant product automated market maker:
              x is the first token
              y is the second token
              k is the constant
              x and y must always multiply to form k`}
            </p>
            <AMMDemonstration />
          </div>
          <div className={styles.section}>
            <h2>Amplified Liquidity Pool</h2>
            <p className={styles.code}> ax * ay = k * a^2</p>
            <p className={styles.description}>
              {`In a dynamic market maker:
              Both x and y are amplified by a
              ax and ay are thus virtual balances
              ax and ay must always multiply to form k * a * a.`}
            </p>
            <DMMDemonstration />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
